version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/next
    ports:
      - "80:80"
    environment:
      - REACT_PORT=80
    restart: always